// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#ifndef _SLS480V2_UI_H
#define _SLS480V2_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_CompassScreen.h"
#include "ui_AttitudeScreen.h"
#include "ui_BrightnessScreen.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * progress_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_45664948);   // assets/Compass-8.png
LV_IMG_DECLARE( ui_img_arrow_png);   // assets/Arrow.png
LV_IMG_DECLARE( ui_img_horizonline_png);   // assets/horizonline.png
LV_IMG_DECLARE( ui_img_578347518);   // assets/icon_light_brightness@3x.png

// FONTS
LV_FONT_DECLARE( ui_font_FontAttitude84c);
LV_FONT_DECLARE( ui_font_FontAttitudeTitle24);
LV_FONT_DECLARE( ui_font_FontDialog36);
LV_FONT_DECLARE( ui_font_FontHeading64b);
LV_FONT_DECLARE( ui_font_FontHeading96b);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
