// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SLS480v3

#ifndef _SLS480V3_UI_H
#define _SLS480V3_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "ui_CompassScreen.h"
#include "ui_AttitudeScreen.h"
#include "ui_BrightnessScreen.h"
#include "ui_WeatherScreen.h"
#include "ui_BatteryScreen.h"
#include "ui_EngineScreen.h"

///////////////////// VARIABLES ////////////////////
extern lv_anim_t * progress_Animation( lv_obj_t *TargetObject, int delay);

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_1776051799);   // assets/Compass-12.png
LV_IMG_DECLARE( ui_img_arrow_png);   // assets/Arrow.png
LV_IMG_DECLARE( ui_img_speedometer_bg_png);   // assets/speedometer_bg.png
LV_IMG_DECLARE( ui_img_222405695);   // assets/caution-2.png
LV_IMG_DECLARE( ui_img_sun3_png);   // assets/sun3.png
LV_IMG_DECLARE( ui_img_temperature2_png);   // assets/temperature2.png
LV_IMG_DECLARE( ui_img_air2_png);   // assets/air2.png
LV_IMG_DECLARE( ui_img_humidity2_png);   // assets/humidity2.png
LV_IMG_DECLARE( ui_img_1299205280);   // assets/car-battery-2.png
LV_IMG_DECLARE( ui_img_454395385);   // assets/exhaust-pipe-2.png
LV_IMG_DECLARE( ui_img_1496861887);   // assets/gas-pump.png
LV_IMG_DECLARE( ui_img_916444405);   // assets/gallon-bottle.png

// FONTS
LV_FONT_DECLARE( ui_font_FontAttitude84c);
LV_FONT_DECLARE( ui_font_FontAttitudeTitle24);
LV_FONT_DECLARE( ui_font_FontDialog36);
LV_FONT_DECLARE( ui_font_FontHeading64b);
LV_FONT_DECLARE( ui_font_FontHeading96b);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
