// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SLS480v3

#include "ui.h"

lv_obj_t *ui_AttitudeScreen = NULL;lv_obj_t *ui_ContainerHorizonGroup = NULL;lv_obj_t *ui_ContainerAttitudeGroup = NULL;lv_obj_t *ui_PanelPitch = NULL;lv_obj_t *ui_LabelPitchTitle = NULL;lv_obj_t *ui_LabelPitch = NULL;lv_obj_t *ui_PanelRoll = NULL;lv_obj_t *ui_LabelRollTitle = NULL;lv_obj_t *ui_LabelRoll = NULL;lv_obj_t *ui_ContainerMinMax = NULL;lv_obj_t *ui_PanelMaxPitch = NULL;lv_obj_t *ui_PanelMinPitch = NULL;lv_obj_t *ui_PanelPitchMinMax = NULL;lv_obj_t *ui_LabelPitchTitleMinMax = NULL;lv_obj_t *ui_LabelMaxPitch = NULL;lv_obj_t *ui_LabelMinPitch = NULL;lv_obj_t *ui_PanelRollMinMax = NULL;lv_obj_t *ui_LabelRollTitleMinMax = NULL;lv_obj_t *ui_LabelMaxRoll = NULL;lv_obj_t *ui_LabelMinRoll = NULL;lv_obj_t *ui_ContainerVessel = NULL;lv_obj_t *ui_PanelHull = NULL;lv_obj_t *ui_PanelDeck = NULL;lv_obj_t *ui_PanelBridge = NULL;lv_obj_t *ui_PanelMast = NULL;lv_obj_t *ui_PanelStarboard = NULL;lv_obj_t *ui_PanelPortside = NULL;
// event funtions

// build funtions

void ui_AttitudeScreen_screen_init(void)
{
ui_AttitudeScreen = lv_obj_create(NULL);
lv_obj_remove_flag( ui_AttitudeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AttitudeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AttitudeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerHorizonGroup = lv_obj_create(ui_AttitudeScreen);
lv_obj_remove_style_all(ui_ContainerHorizonGroup);
lv_obj_set_width( ui_ContainerHorizonGroup, 680);
lv_obj_set_height( ui_ContainerHorizonGroup, 680);
lv_obj_set_align( ui_ContainerHorizonGroup, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_ContainerHorizonGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_ContainerAttitudeGroup = lv_obj_create(ui_AttitudeScreen);
lv_obj_remove_style_all(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_ContainerAttitudeGroup, 484);
lv_obj_set_height( ui_ContainerAttitudeGroup, 484);
lv_obj_set_align( ui_ContainerAttitudeGroup, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_ContainerAttitudeGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_border_color(ui_ContainerAttitudeGroup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ContainerAttitudeGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPitch = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelPitch, 280);
lv_obj_set_height( ui_PanelPitch, 140);
lv_obj_set_x( ui_PanelPitch, 0 );
lv_obj_set_y( ui_PanelPitch, -160 );
lv_obj_set_align( ui_PanelPitch, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelPitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelPitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPitch, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPitchTitle = lv_label_create(ui_PanelPitch);
lv_obj_set_width( ui_LabelPitchTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPitchTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPitchTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelPitchTitle,"Pitch");
lv_obj_remove_flag( ui_LabelPitchTitle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelPitchTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPitchTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPitchTitle, &ui_font_FontAttitudeTitle24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPitch = lv_label_create(ui_PanelPitch);
lv_obj_set_width( ui_LabelPitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPitch, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelPitch,"+000°");
lv_obj_remove_flag( ui_LabelPitch, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelPitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPitch, &ui_font_FontAttitude84c, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelRoll = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelRoll, 280);
lv_obj_set_height( ui_PanelRoll, 140);
lv_obj_set_x( ui_PanelRoll, 0 );
lv_obj_set_y( ui_PanelRoll, 160 );
lv_obj_set_align( ui_PanelRoll, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelRoll, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelRoll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelRoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelRoll, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelRoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRollTitle = lv_label_create(ui_PanelRoll);
lv_obj_set_width( ui_LabelRollTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRollTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelRollTitle, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelRollTitle,"Roll");
lv_obj_remove_flag( ui_LabelRollTitle, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelRollTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRollTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRollTitle, &ui_font_FontAttitudeTitle24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRoll = lv_label_create(ui_PanelRoll);
lv_obj_set_width( ui_LabelRoll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRoll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelRoll, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelRoll,"-000°");
lv_obj_remove_flag( ui_LabelRoll, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRoll, &ui_font_FontAttitude84c, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerMinMax = lv_obj_create(ui_AttitudeScreen);
lv_obj_remove_style_all(ui_ContainerMinMax);
lv_obj_set_width( ui_ContainerMinMax, 484);
lv_obj_set_height( ui_ContainerMinMax, 484);
lv_obj_set_align( ui_ContainerMinMax, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ContainerMinMax, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_remove_flag( ui_ContainerMinMax, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_PanelMaxPitch = lv_obj_create(ui_ContainerMinMax);
lv_obj_set_width( ui_PanelMaxPitch, 484);
lv_obj_set_height( ui_PanelMaxPitch, 4);
lv_obj_set_align( ui_PanelMaxPitch, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelMaxPitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelMaxPitch, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMaxPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMaxPitch, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMaxPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMinPitch = lv_obj_create(ui_ContainerMinMax);
lv_obj_set_width( ui_PanelMinPitch, 484);
lv_obj_set_height( ui_PanelMinPitch, 4);
lv_obj_set_align( ui_PanelMinPitch, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelMinPitch, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelMinPitch, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMinPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMinPitch, lv_color_hex(0x0000FF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMinPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPitchMinMax = lv_obj_create(ui_ContainerMinMax);
lv_obj_set_width( ui_PanelPitchMinMax, 280);
lv_obj_set_height( ui_PanelPitchMinMax, 140);
lv_obj_set_x( ui_PanelPitchMinMax, 0 );
lv_obj_set_y( ui_PanelPitchMinMax, -160 );
lv_obj_set_align( ui_PanelPitchMinMax, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelPitchMinMax, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelPitchMinMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPitchMinMax, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPitchMinMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPitchMinMax, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPitchTitleMinMax = lv_label_create(ui_PanelPitchMinMax);
lv_obj_set_width( ui_LabelPitchTitleMinMax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPitchTitleMinMax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPitchTitleMinMax, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelPitchTitleMinMax,"Pitch");
lv_obj_remove_flag( ui_LabelPitchTitleMinMax, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelPitchTitleMinMax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPitchTitleMinMax, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPitchTitleMinMax, &ui_font_FontAttitudeTitle24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxPitch = lv_label_create(ui_PanelPitchMinMax);
lv_obj_set_width( ui_LabelMaxPitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxPitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxPitch, 0 );
lv_obj_set_y( ui_LabelMaxPitch, -10 );
lv_obj_set_align( ui_LabelMaxPitch, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxPitch,"Max +090°");
lv_obj_remove_flag( ui_LabelMaxPitch, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxPitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxPitch, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinPitch = lv_label_create(ui_PanelPitchMinMax);
lv_obj_set_width( ui_LabelMinPitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinPitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinPitch, 0 );
lv_obj_set_y( ui_LabelMinPitch, 25 );
lv_obj_set_align( ui_LabelMinPitch, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinPitch,"Min -090°");
lv_obj_remove_flag( ui_LabelMinPitch, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinPitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinPitch, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelRollMinMax = lv_obj_create(ui_ContainerMinMax);
lv_obj_set_width( ui_PanelRollMinMax, 280);
lv_obj_set_height( ui_PanelRollMinMax, 140);
lv_obj_set_x( ui_PanelRollMinMax, 0 );
lv_obj_set_y( ui_PanelRollMinMax, 160 );
lv_obj_set_align( ui_PanelRollMinMax, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelRollMinMax, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelRollMinMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelRollMinMax, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelRollMinMax, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelRollMinMax, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRollTitleMinMax = lv_label_create(ui_PanelRollMinMax);
lv_obj_set_width( ui_LabelRollTitleMinMax, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRollTitleMinMax, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelRollTitleMinMax, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelRollTitleMinMax,"Roll");
lv_obj_remove_flag( ui_LabelRollTitleMinMax, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelRollTitleMinMax, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRollTitleMinMax, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRollTitleMinMax, &ui_font_FontAttitudeTitle24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxRoll = lv_label_create(ui_PanelRollMinMax);
lv_obj_set_width( ui_LabelMaxRoll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxRoll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxRoll, 0 );
lv_obj_set_y( ui_LabelMaxRoll, -20 );
lv_obj_set_align( ui_LabelMaxRoll, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxRoll,"Max +090°");
lv_obj_remove_flag( ui_LabelMaxRoll, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxRoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxRoll, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinRoll = lv_label_create(ui_PanelRollMinMax);
lv_obj_set_width( ui_LabelMinRoll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinRoll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinRoll, 0 );
lv_obj_set_y( ui_LabelMinRoll, 15 );
lv_obj_set_align( ui_LabelMinRoll, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinRoll,"Min -090°");
lv_obj_remove_flag( ui_LabelMinRoll, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinRoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinRoll, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerVessel = lv_obj_create(ui_AttitudeScreen);
lv_obj_remove_style_all(ui_ContainerVessel);
lv_obj_set_width( ui_ContainerVessel, 240);
lv_obj_set_height( ui_ContainerVessel, 240);
lv_obj_set_align( ui_ContainerVessel, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_ContainerVessel, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_PanelHull = lv_obj_create(ui_ContainerVessel);
lv_obj_set_width( ui_PanelHull, 100);
lv_obj_set_height( ui_PanelHull, 100);
lv_obj_set_x( ui_PanelHull, 0 );
lv_obj_set_y( ui_PanelHull, 5 );
lv_obj_set_align( ui_PanelHull, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelHull, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PanelHull, 256, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelDeck = lv_obj_create(ui_ContainerVessel);
lv_obj_set_width( ui_PanelDeck, 100);
lv_obj_set_height( ui_PanelDeck, 50);
lv_obj_set_x( ui_PanelDeck, 0 );
lv_obj_set_y( ui_PanelDeck, -15 );
lv_obj_set_align( ui_PanelDeck, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelDeck, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PanelDeck, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelDeck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelDeck, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelDeck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelDeck, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelBridge = lv_obj_create(ui_ContainerVessel);
lv_obj_set_width( ui_PanelBridge, 56);
lv_obj_set_height( ui_PanelBridge, 30);
lv_obj_set_x( ui_PanelBridge, 0 );
lv_obj_set_y( ui_PanelBridge, -55 );
lv_obj_set_align( ui_PanelBridge, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelBridge, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PanelBridge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelBridge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelBridge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelBridge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelBridge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMast = lv_obj_create(ui_ContainerVessel);
lv_obj_set_width( ui_PanelMast, 6);
lv_obj_set_height( ui_PanelMast, 35);
lv_obj_set_x( ui_PanelMast, 0 );
lv_obj_set_y( ui_PanelMast, -85 );
lv_obj_set_align( ui_PanelMast, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelMast, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PanelMast, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelMast, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMast, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMast, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMast, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelStarboard = lv_obj_create(ui_ContainerVessel);
lv_obj_set_width( ui_PanelStarboard, 20);
lv_obj_set_height( ui_PanelStarboard, 20);
lv_obj_set_x( ui_PanelStarboard, 48 );
lv_obj_set_y( ui_PanelStarboard, -40 );
lv_obj_set_align( ui_PanelStarboard, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelStarboard, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PanelStarboard, 256, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelStarboard, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelStarboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelStarboard, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelStarboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPortside = lv_obj_create(ui_ContainerVessel);
lv_obj_set_width( ui_PanelPortside, 20);
lv_obj_set_height( ui_PanelPortside, 20);
lv_obj_set_x( ui_PanelPortside, -48 );
lv_obj_set_y( ui_PanelPortside, -40 );
lv_obj_set_align( ui_PanelPortside, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_PanelPortside, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_radius(ui_PanelPortside, 256, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelPortside, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPortside, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPortside, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPortside, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_AttitudeScreen_screen_destroy(void)
{
   if (ui_AttitudeScreen) lv_obj_del(ui_AttitudeScreen);

// NULL screen variables
ui_AttitudeScreen= NULL;
ui_ContainerHorizonGroup= NULL;
ui_ContainerAttitudeGroup= NULL;
ui_PanelPitch= NULL;
ui_LabelPitchTitle= NULL;
ui_LabelPitch= NULL;
ui_PanelRoll= NULL;
ui_LabelRollTitle= NULL;
ui_LabelRoll= NULL;
ui_ContainerMinMax= NULL;
ui_PanelMaxPitch= NULL;
ui_PanelMinPitch= NULL;
ui_PanelPitchMinMax= NULL;
ui_LabelPitchTitleMinMax= NULL;
ui_LabelMaxPitch= NULL;
ui_LabelMinPitch= NULL;
ui_PanelRollMinMax= NULL;
ui_LabelRollTitleMinMax= NULL;
ui_LabelMaxRoll= NULL;
ui_LabelMinRoll= NULL;
ui_ContainerVessel= NULL;
ui_PanelHull= NULL;
ui_PanelDeck= NULL;
ui_PanelBridge= NULL;
ui_PanelMast= NULL;
ui_PanelStarboard= NULL;
ui_PanelPortside= NULL;

}
