// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#ifndef UI_ATTITUDESCREEN_H
#define UI_ATTITUDESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AttitudeScreen
extern void ui_AttitudeScreen_screen_init(void);
extern void ui_AttitudeScreen_screen_destroy(void);
extern lv_obj_t *ui_AttitudeScreen;
extern lv_obj_t *ui_ContainerHorizonGroup;
extern lv_obj_t *ui_ImageHorizon;
extern lv_obj_t *ui_ContainerAttitudeGroup;
extern lv_obj_t *ui_PanelPitch;
extern lv_obj_t *ui_LabelPitchTitle;
extern lv_obj_t *ui_LabelPitch;
extern lv_obj_t *ui_PanelRoll;
extern lv_obj_t *ui_LabelRollTitle;
extern lv_obj_t *ui_LabelRoll;
extern lv_obj_t *ui_PanelHull;
extern lv_obj_t *ui_PanelDeck;
extern lv_obj_t *ui_PanelBridge;
extern lv_obj_t *ui_PanelMast;
extern lv_obj_t *ui_PanelStarboard;
extern lv_obj_t *ui_PanelPortside;
extern lv_obj_t *ui_ContainerLevelingDialog;
extern lv_obj_t *ui_PanelLevelingDialog;
extern lv_obj_t *ui_LabelLevelingDialog;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

