// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#include "ui.h"

lv_obj_t *ui_AttitudeScreen = NULL;lv_obj_t *ui_ContainerHorizonGroup = NULL;lv_obj_t *ui_ImageHorizon = NULL;lv_obj_t *ui_ContainerAttitudeGroup = NULL;lv_obj_t *ui_PanelPitch = NULL;lv_obj_t *ui_LabelPitchTitle = NULL;lv_obj_t *ui_LabelPitch = NULL;lv_obj_t *ui_PanelRoll = NULL;lv_obj_t *ui_LabelRollTitle = NULL;lv_obj_t *ui_LabelRoll = NULL;lv_obj_t *ui_PanelHull = NULL;lv_obj_t *ui_PanelDeck = NULL;lv_obj_t *ui_PanelBridge = NULL;lv_obj_t *ui_PanelMast = NULL;lv_obj_t *ui_PanelStarboard = NULL;lv_obj_t *ui_PanelPortside = NULL;lv_obj_t *ui_ContainerLevelingDialog = NULL;lv_obj_t *ui_PanelLevelingDialog = NULL;lv_obj_t *ui_LabelLevelingDialog = NULL;
// event funtions

// build funtions

void ui_AttitudeScreen_screen_init(void)
{
ui_AttitudeScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_AttitudeScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_AttitudeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_AttitudeScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerHorizonGroup = lv_obj_create(ui_AttitudeScreen);
lv_obj_remove_style_all(ui_ContainerHorizonGroup);
lv_obj_set_width( ui_ContainerHorizonGroup, 680);
lv_obj_set_height( ui_ContainerHorizonGroup, 680);
lv_obj_set_align( ui_ContainerHorizonGroup, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ContainerHorizonGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ImageHorizon = lv_img_create(ui_ContainerHorizonGroup);
lv_img_set_src(ui_ImageHorizon, &ui_img_horizonline_png);
lv_obj_set_width( ui_ImageHorizon, 680);
lv_obj_set_height( ui_ImageHorizon, 4);
lv_obj_set_align( ui_ImageHorizon, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ImageHorizon, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_ImageHorizon, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ContainerAttitudeGroup = lv_obj_create(ui_AttitudeScreen);
lv_obj_remove_style_all(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_ContainerAttitudeGroup, 484);
lv_obj_set_height( ui_ContainerAttitudeGroup, 484);
lv_obj_set_align( ui_ContainerAttitudeGroup, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_ContainerAttitudeGroup, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_border_color(ui_ContainerAttitudeGroup, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ContainerAttitudeGroup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPitch = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelPitch, 280);
lv_obj_set_height( ui_PanelPitch, 140);
lv_obj_set_x( ui_PanelPitch, 0 );
lv_obj_set_y( ui_PanelPitch, -140 );
lv_obj_set_align( ui_PanelPitch, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPitch, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelPitch, lv_color_hex(0x78B4F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPitch, lv_color_hex(0x78B4F0), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPitch, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPitchTitle = lv_label_create(ui_PanelPitch);
lv_obj_set_width( ui_LabelPitchTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPitchTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPitchTitle, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelPitchTitle,"Pitch");
lv_obj_set_style_text_color(ui_LabelPitchTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPitchTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPitchTitle, &ui_font_FontAttitudeTitle24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelPitch = lv_label_create(ui_PanelPitch);
lv_obj_set_width( ui_LabelPitch, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPitch, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPitch, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelPitch,"+000°");
lv_obj_set_style_text_color(ui_LabelPitch, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPitch, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPitch, &ui_font_FontAttitude84c, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelRoll = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelRoll, 280);
lv_obj_set_height( ui_PanelRoll, 140);
lv_obj_set_x( ui_PanelRoll, 0 );
lv_obj_set_y( ui_PanelRoll, 140 );
lv_obj_set_align( ui_PanelRoll, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelRoll, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelRoll, lv_color_hex(0x192864), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelRoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelRoll, lv_color_hex(0x192864), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelRoll, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRollTitle = lv_label_create(ui_PanelRoll);
lv_obj_set_width( ui_LabelRollTitle, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRollTitle, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelRollTitle, LV_ALIGN_BOTTOM_MID );
lv_label_set_text(ui_LabelRollTitle,"Roll");
lv_obj_set_style_text_color(ui_LabelRollTitle, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRollTitle, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRollTitle, &ui_font_FontAttitudeTitle24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelRoll = lv_label_create(ui_PanelRoll);
lv_obj_set_width( ui_LabelRoll, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelRoll, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelRoll, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_LabelRoll,"-000°");
lv_obj_set_style_text_color(ui_LabelRoll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelRoll, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelRoll, &ui_font_FontAttitude84c, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHull = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelHull, 50);
lv_obj_set_height( ui_PanelHull, 50);
lv_obj_set_align( ui_PanelHull, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelHull, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelHull, 256, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelDeck = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelDeck, 50);
lv_obj_set_height( ui_PanelDeck, 25);
lv_obj_set_x( ui_PanelDeck, 0 );
lv_obj_set_y( ui_PanelDeck, -12 );
lv_obj_set_align( ui_PanelDeck, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelDeck, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelDeck, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelDeck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelDeck, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelDeck, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelDeck, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelBridge = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelBridge, 30);
lv_obj_set_height( ui_PanelBridge, 12);
lv_obj_set_x( ui_PanelBridge, 0 );
lv_obj_set_y( ui_PanelBridge, -30 );
lv_obj_set_align( ui_PanelBridge, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelBridge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelBridge, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelBridge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelBridge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelBridge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelBridge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelMast = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelMast, 2);
lv_obj_set_height( ui_PanelMast, 25);
lv_obj_set_x( ui_PanelMast, 0 );
lv_obj_set_y( ui_PanelMast, -45 );
lv_obj_set_align( ui_PanelMast, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelMast, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PanelMast, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PanelMast, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelMast, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelMast, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelMast, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelStarboard = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelStarboard, 10);
lv_obj_set_height( ui_PanelStarboard, 10);
lv_obj_set_x( ui_PanelStarboard, 25 );
lv_obj_set_y( ui_PanelStarboard, -20 );
lv_obj_set_align( ui_PanelStarboard, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelStarboard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelStarboard, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelStarboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelStarboard, lv_color_hex(0x00FF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelStarboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPortside = lv_obj_create(ui_ContainerAttitudeGroup);
lv_obj_set_width( ui_PanelPortside, 10);
lv_obj_set_height( ui_PanelPortside, 10);
lv_obj_set_x( ui_PanelPortside, -25 );
lv_obj_set_y( ui_PanelPortside, -20 );
lv_obj_set_align( ui_PanelPortside, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelPortside, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelPortside, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPortside, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPortside, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPortside, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContainerLevelingDialog = lv_obj_create(ui_AttitudeScreen);
lv_obj_remove_style_all(ui_ContainerLevelingDialog);
lv_obj_set_width( ui_ContainerLevelingDialog, 484);
lv_obj_set_height( ui_ContainerLevelingDialog, 484);
lv_obj_set_align( ui_ContainerLevelingDialog, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ContainerLevelingDialog, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_ContainerLevelingDialog, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ContainerLevelingDialog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ContainerLevelingDialog, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_ContainerLevelingDialog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_ContainerLevelingDialog, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelLevelingDialog = lv_obj_create(ui_ContainerLevelingDialog);
lv_obj_set_width( ui_PanelLevelingDialog, 484);
lv_obj_set_height( ui_PanelLevelingDialog, 484);
lv_obj_set_align( ui_PanelLevelingDialog, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelLevelingDialog, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_PanelLevelingDialog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelLevelingDialog, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelLevelingDialog, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelLevelingDialog, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelLevelingDialog = lv_label_create(ui_PanelLevelingDialog);
lv_obj_set_width( ui_LabelLevelingDialog, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelLevelingDialog, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelLevelingDialog, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelLevelingDialog,"Level attitude?\n\nPress knob again\nto confirm.");
lv_obj_set_style_text_color(ui_LabelLevelingDialog, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelLevelingDialog, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LabelLevelingDialog, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelLevelingDialog, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_AttitudeScreen_screen_destroy(void)
{
   if (ui_AttitudeScreen) lv_obj_del(ui_AttitudeScreen);

// NULL screen variables
ui_AttitudeScreen= NULL;
ui_ContainerHorizonGroup= NULL;
ui_ImageHorizon= NULL;
ui_ContainerAttitudeGroup= NULL;
ui_PanelPitch= NULL;
ui_LabelPitchTitle= NULL;
ui_LabelPitch= NULL;
ui_PanelRoll= NULL;
ui_LabelRollTitle= NULL;
ui_LabelRoll= NULL;
ui_PanelHull= NULL;
ui_PanelDeck= NULL;
ui_PanelBridge= NULL;
ui_PanelMast= NULL;
ui_PanelStarboard= NULL;
ui_PanelPortside= NULL;
ui_ContainerLevelingDialog= NULL;
ui_PanelLevelingDialog= NULL;
ui_LabelLevelingDialog= NULL;

}
