// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SLS480v3

#ifndef UI_ATTITUDESCREEN_H
#define UI_ATTITUDESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AttitudeScreen
extern void ui_AttitudeScreen_screen_init(void);
extern void ui_AttitudeScreen_screen_destroy(void);
extern lv_obj_t *ui_AttitudeScreen;
extern lv_obj_t *ui_ContainerHorizonGroup;
extern lv_obj_t *ui_ImageHorizon;
extern lv_obj_t *ui_ContainerAttitudeGroup;
extern lv_obj_t *ui_PanelPitch;
extern lv_obj_t *ui_LabelPitchTitle;
extern lv_obj_t *ui_LabelPitch;
extern lv_obj_t *ui_PanelRoll;
extern lv_obj_t *ui_LabelRollTitle;
extern lv_obj_t *ui_LabelRoll;
extern lv_obj_t *ui_ContainerMinMax;
extern lv_obj_t *ui_PanelMaxPitch;
extern lv_obj_t *ui_PanelMinPitch;
extern lv_obj_t *ui_PanelMaxRoll;
extern lv_obj_t *ui_PanelMinRoll;
extern lv_obj_t *ui_PanelPitchMinMax;
extern lv_obj_t *ui_LabelPitchTitleMinMax;
extern lv_obj_t *ui_LabelMaxPitch;
extern lv_obj_t *ui_LabelMinPitch;
extern lv_obj_t *ui_PanelRollMinMax;
extern lv_obj_t *ui_LabelRollTitleMinMax;
extern lv_obj_t *ui_LabelMaxRoll;
extern lv_obj_t *ui_LabelMinRoll;
extern lv_obj_t *ui_ContainerVessel;
extern lv_obj_t *ui_PanelHull;
extern lv_obj_t *ui_PanelDeck;
extern lv_obj_t *ui_PanelBridge;
extern lv_obj_t *ui_PanelMast;
extern lv_obj_t *ui_PanelStarboard;
extern lv_obj_t *ui_PanelPortside;
extern lv_obj_t *ui_ContainerLevelingDialog;
extern lv_obj_t *ui_PanelLevelingDialog;
extern lv_obj_t *ui_LabelLevelingDialog;
extern lv_obj_t *ui_LabelLevelingCancel;
extern lv_obj_t *ui_ImageBubbleLevel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

