// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#ifndef UI_BRIGHTNESSSCREEN_H
#define UI_BRIGHTNESSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BrightnessScreen
extern void ui_BrightnessScreen_screen_init(void);
extern void ui_BrightnessScreen_screen_destroy(void);
extern lv_obj_t *ui_BrightnessScreen;
extern lv_obj_t *ui_ContainerBrightness;
extern lv_obj_t *ui_PanelBrightness;
extern lv_obj_t *ui_ImageBrightness;
extern lv_obj_t *ui_LabelBrightness;
extern lv_obj_t *ui_LabelBrightnessValue;
extern lv_obj_t *ui_ContainerAdjustment;
extern lv_obj_t *ui_ArcAdjustment;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

