// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#ifndef UI_BATTERYSCREEN_H
#define UI_BATTERYSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BatteryScreen
extern void ui_BatteryScreen_screen_init(void);
extern void ui_BatteryScreen_screen_destroy(void);
extern lv_obj_t *ui_BatteryScreen;
extern lv_obj_t *ui_PanelHouseVoltage;
extern lv_obj_t *ui_LabelHouseVoltage;
extern lv_obj_t *ui_LabelMaxHouseVoltage;
extern lv_obj_t *ui_LabelMinHouseVoltage;
extern lv_obj_t *ui_LabelHouseVoltageTrend;
extern lv_obj_t *ui_PanelHouseAmps;
extern lv_obj_t *ui_LabelHouseAmps;
extern lv_obj_t *ui_LabelMaxHouseAmps;
extern lv_obj_t *ui_LabelMinHouseAmps;
extern lv_obj_t *ui_LabelHouseAmpsTrend;
extern lv_obj_t *ui_PanelHouseSoc;
extern lv_obj_t *ui_LabelHouseSoc;
extern lv_obj_t *ui_LabelMaxHouseSoc;
extern lv_obj_t *ui_LabelMinHouseSoc;
extern lv_obj_t *ui_LabelHouseSocTrend;
extern lv_obj_t *ui_PanelStarterVoltage;
extern lv_obj_t *ui_LabelStarterVoltage;
extern lv_obj_t *ui_LabelMaxStarterVoltage;
extern lv_obj_t *ui_LabelMinStarterVoltage;
extern lv_obj_t *ui_LabelStarterVoltageTrend;
extern lv_obj_t *ui_ImageBattery;
extern lv_obj_t *ui_LabelHouse;
extern lv_obj_t *ui_LabelStarter;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

