// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#include "ui.h"

lv_obj_t *ui_BatteryScreen = NULL;lv_obj_t *ui_PanelHouseVoltage = NULL;lv_obj_t *ui_LabelHouseVoltage = NULL;lv_obj_t *ui_LabelMaxHouseVoltage = NULL;lv_obj_t *ui_LabelMinHouseVoltage = NULL;lv_obj_t *ui_LabelHouseVoltageTrend = NULL;lv_obj_t *ui_PanelHouseAmps = NULL;lv_obj_t *ui_LabelHouseAmps = NULL;lv_obj_t *ui_LabelMaxHouseAmps = NULL;lv_obj_t *ui_LabelMinHouseAmps = NULL;lv_obj_t *ui_LabelHouseAmpsTrend = NULL;lv_obj_t *ui_PanelHouseSoc = NULL;lv_obj_t *ui_LabelHouseSoc = NULL;lv_obj_t *ui_LabelMaxHouseSoc = NULL;lv_obj_t *ui_LabelMinHouseSoc = NULL;lv_obj_t *ui_LabelHouseSocTrend = NULL;lv_obj_t *ui_PanelStarterVoltage = NULL;lv_obj_t *ui_LabelStarterVoltage = NULL;lv_obj_t *ui_LabelMaxStarterVoltage = NULL;lv_obj_t *ui_LabelMinStarterVoltage = NULL;lv_obj_t *ui_LabelStarterVoltageTrend = NULL;lv_obj_t *ui_ImageBattery = NULL;lv_obj_t *ui_LabelHouse = NULL;lv_obj_t *ui_LabelStarter = NULL;
// event funtions

// build funtions

void ui_BatteryScreen_screen_init(void)
{
ui_BatteryScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_BatteryScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_BatteryScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatteryScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHouseVoltage = lv_obj_create(ui_BatteryScreen);
lv_obj_set_width( ui_PanelHouseVoltage, 480);
lv_obj_set_height( ui_PanelHouseVoltage, 480);
lv_obj_set_align( ui_PanelHouseVoltage, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelHouseVoltage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelHouseVoltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelHouseVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelHouseVoltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelHouseVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHouseVoltage = lv_label_create(ui_PanelHouseVoltage);
lv_obj_set_width( ui_LabelHouseVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHouseVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHouseVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHouseVoltage,"25.5V");
lv_obj_clear_flag( ui_LabelHouseVoltage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHouseVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHouseVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHouseVoltage, &ui_font_FontHeading96b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxHouseVoltage = lv_label_create(ui_PanelHouseVoltage);
lv_obj_set_width( ui_LabelMaxHouseVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxHouseVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxHouseVoltage, 0 );
lv_obj_set_y( ui_LabelMaxHouseVoltage, 120 );
lv_obj_set_align( ui_LabelMaxHouseVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxHouseVoltage,"Max 40.0V");
lv_obj_clear_flag( ui_LabelMaxHouseVoltage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxHouseVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxHouseVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxHouseVoltage, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinHouseVoltage = lv_label_create(ui_PanelHouseVoltage);
lv_obj_set_width( ui_LabelMinHouseVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinHouseVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinHouseVoltage, 0 );
lv_obj_set_y( ui_LabelMinHouseVoltage, 160 );
lv_obj_set_align( ui_LabelMinHouseVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinHouseVoltage,"Min 0.0V");
lv_obj_clear_flag( ui_LabelMinHouseVoltage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinHouseVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinHouseVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinHouseVoltage, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHouseVoltageTrend = lv_label_create(ui_PanelHouseVoltage);
lv_obj_set_width( ui_LabelHouseVoltageTrend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHouseVoltageTrend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHouseVoltageTrend, 0 );
lv_obj_set_y( ui_LabelHouseVoltageTrend, 80 );
lv_obj_set_align( ui_LabelHouseVoltageTrend, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHouseVoltageTrend,"↓↑");
lv_obj_clear_flag( ui_LabelHouseVoltageTrend, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHouseVoltageTrend, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHouseVoltageTrend, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHouseVoltageTrend, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHouseAmps = lv_obj_create(ui_BatteryScreen);
lv_obj_set_width( ui_PanelHouseAmps, 480);
lv_obj_set_height( ui_PanelHouseAmps, 480);
lv_obj_set_align( ui_PanelHouseAmps, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PanelHouseAmps, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelHouseAmps, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelHouseAmps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelHouseAmps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelHouseAmps, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelHouseAmps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHouseAmps = lv_label_create(ui_PanelHouseAmps);
lv_obj_set_width( ui_LabelHouseAmps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHouseAmps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHouseAmps, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHouseAmps,"+10.0A");
lv_obj_clear_flag( ui_LabelHouseAmps, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHouseAmps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHouseAmps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHouseAmps, &ui_font_FontHeading96b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxHouseAmps = lv_label_create(ui_PanelHouseAmps);
lv_obj_set_width( ui_LabelMaxHouseAmps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxHouseAmps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxHouseAmps, 0 );
lv_obj_set_y( ui_LabelMaxHouseAmps, 120 );
lv_obj_set_align( ui_LabelMaxHouseAmps, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxHouseAmps,"Max +200.0A");
lv_obj_clear_flag( ui_LabelMaxHouseAmps, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxHouseAmps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxHouseAmps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxHouseAmps, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinHouseAmps = lv_label_create(ui_PanelHouseAmps);
lv_obj_set_width( ui_LabelMinHouseAmps, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinHouseAmps, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinHouseAmps, 0 );
lv_obj_set_y( ui_LabelMinHouseAmps, 160 );
lv_obj_set_align( ui_LabelMinHouseAmps, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinHouseAmps,"Min -200.0A");
lv_obj_clear_flag( ui_LabelMinHouseAmps, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinHouseAmps, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinHouseAmps, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinHouseAmps, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHouseAmpsTrend = lv_label_create(ui_PanelHouseAmps);
lv_obj_set_width( ui_LabelHouseAmpsTrend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHouseAmpsTrend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHouseAmpsTrend, 0 );
lv_obj_set_y( ui_LabelHouseAmpsTrend, 80 );
lv_obj_set_align( ui_LabelHouseAmpsTrend, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHouseAmpsTrend,"↓↑");
lv_obj_clear_flag( ui_LabelHouseAmpsTrend, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHouseAmpsTrend, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHouseAmpsTrend, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHouseAmpsTrend, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHouseSoc = lv_obj_create(ui_BatteryScreen);
lv_obj_set_width( ui_PanelHouseSoc, 480);
lv_obj_set_height( ui_PanelHouseSoc, 480);
lv_obj_set_align( ui_PanelHouseSoc, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PanelHouseSoc, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelHouseSoc, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelHouseSoc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelHouseSoc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelHouseSoc, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelHouseSoc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHouseSoc = lv_label_create(ui_PanelHouseSoc);
lv_obj_set_width( ui_LabelHouseSoc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHouseSoc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHouseSoc, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHouseSoc,"100%");
lv_obj_clear_flag( ui_LabelHouseSoc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHouseSoc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHouseSoc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHouseSoc, &ui_font_FontHeading96b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxHouseSoc = lv_label_create(ui_PanelHouseSoc);
lv_obj_set_width( ui_LabelMaxHouseSoc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxHouseSoc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxHouseSoc, 0 );
lv_obj_set_y( ui_LabelMaxHouseSoc, 120 );
lv_obj_set_align( ui_LabelMaxHouseSoc, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxHouseSoc,"Max 100%");
lv_obj_clear_flag( ui_LabelMaxHouseSoc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxHouseSoc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxHouseSoc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxHouseSoc, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinHouseSoc = lv_label_create(ui_PanelHouseSoc);
lv_obj_set_width( ui_LabelMinHouseSoc, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinHouseSoc, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinHouseSoc, 0 );
lv_obj_set_y( ui_LabelMinHouseSoc, 160 );
lv_obj_set_align( ui_LabelMinHouseSoc, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinHouseSoc,"Min 0%");
lv_obj_clear_flag( ui_LabelMinHouseSoc, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinHouseSoc, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinHouseSoc, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinHouseSoc, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHouseSocTrend = lv_label_create(ui_PanelHouseSoc);
lv_obj_set_width( ui_LabelHouseSocTrend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHouseSocTrend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHouseSocTrend, 0 );
lv_obj_set_y( ui_LabelHouseSocTrend, 80 );
lv_obj_set_align( ui_LabelHouseSocTrend, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHouseSocTrend,"↓↑");
lv_obj_clear_flag( ui_LabelHouseSocTrend, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHouseSocTrend, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHouseSocTrend, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHouseSocTrend, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelStarterVoltage = lv_obj_create(ui_BatteryScreen);
lv_obj_set_width( ui_PanelStarterVoltage, 480);
lv_obj_set_height( ui_PanelStarterVoltage, 480);
lv_obj_set_align( ui_PanelStarterVoltage, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PanelStarterVoltage, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelStarterVoltage, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelStarterVoltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelStarterVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelStarterVoltage, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelStarterVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelStarterVoltage = lv_label_create(ui_PanelStarterVoltage);
lv_obj_set_width( ui_LabelStarterVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStarterVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelStarterVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStarterVoltage,"25.5V");
lv_obj_clear_flag( ui_LabelStarterVoltage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelStarterVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStarterVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelStarterVoltage, &ui_font_FontHeading96b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxStarterVoltage = lv_label_create(ui_PanelStarterVoltage);
lv_obj_set_width( ui_LabelMaxStarterVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxStarterVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxStarterVoltage, 0 );
lv_obj_set_y( ui_LabelMaxStarterVoltage, 120 );
lv_obj_set_align( ui_LabelMaxStarterVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxStarterVoltage,"Max 40.0V");
lv_obj_clear_flag( ui_LabelMaxStarterVoltage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxStarterVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxStarterVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxStarterVoltage, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinStarterVoltage = lv_label_create(ui_PanelStarterVoltage);
lv_obj_set_width( ui_LabelMinStarterVoltage, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinStarterVoltage, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinStarterVoltage, 0 );
lv_obj_set_y( ui_LabelMinStarterVoltage, 160 );
lv_obj_set_align( ui_LabelMinStarterVoltage, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinStarterVoltage,"Min 0.0V");
lv_obj_clear_flag( ui_LabelMinStarterVoltage, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinStarterVoltage, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinStarterVoltage, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinStarterVoltage, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelStarterVoltageTrend = lv_label_create(ui_PanelStarterVoltage);
lv_obj_set_width( ui_LabelStarterVoltageTrend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStarterVoltageTrend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStarterVoltageTrend, 0 );
lv_obj_set_y( ui_LabelStarterVoltageTrend, 80 );
lv_obj_set_align( ui_LabelStarterVoltageTrend, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStarterVoltageTrend,"↓↑");
lv_obj_clear_flag( ui_LabelStarterVoltageTrend, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelStarterVoltageTrend, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStarterVoltageTrend, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelStarterVoltageTrend, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageBattery = lv_img_create(ui_BatteryScreen);
lv_img_set_src(ui_ImageBattery, &ui_img_1299205280);
lv_obj_set_width( ui_ImageBattery, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageBattery, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageBattery, 0 );
lv_obj_set_y( ui_ImageBattery, 14 );
lv_obj_set_align( ui_ImageBattery, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ImageBattery, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_LabelHouse = lv_label_create(ui_BatteryScreen);
lv_obj_set_width( ui_LabelHouse, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHouse, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHouse, 0 );
lv_obj_set_y( ui_LabelHouse, -80 );
lv_obj_set_align( ui_LabelHouse, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHouse,"House");
lv_obj_clear_flag( ui_LabelHouse, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHouse, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHouse, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHouse, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelStarter = lv_label_create(ui_BatteryScreen);
lv_obj_set_width( ui_LabelStarter, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelStarter, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelStarter, 0 );
lv_obj_set_y( ui_LabelStarter, -80 );
lv_obj_set_align( ui_LabelStarter, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelStarter,"Start");
lv_obj_add_flag( ui_LabelStarter, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_LabelStarter, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelStarter, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelStarter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelStarter, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_BatteryScreen_screen_destroy(void)
{
   if (ui_BatteryScreen) lv_obj_del(ui_BatteryScreen);

// NULL screen variables
ui_BatteryScreen= NULL;
ui_PanelHouseVoltage= NULL;
ui_LabelHouseVoltage= NULL;
ui_LabelMaxHouseVoltage= NULL;
ui_LabelMinHouseVoltage= NULL;
ui_LabelHouseVoltageTrend= NULL;
ui_PanelHouseAmps= NULL;
ui_LabelHouseAmps= NULL;
ui_LabelMaxHouseAmps= NULL;
ui_LabelMinHouseAmps= NULL;
ui_LabelHouseAmpsTrend= NULL;
ui_PanelHouseSoc= NULL;
ui_LabelHouseSoc= NULL;
ui_LabelMaxHouseSoc= NULL;
ui_LabelMinHouseSoc= NULL;
ui_LabelHouseSocTrend= NULL;
ui_PanelStarterVoltage= NULL;
ui_LabelStarterVoltage= NULL;
ui_LabelMaxStarterVoltage= NULL;
ui_LabelMinStarterVoltage= NULL;
ui_LabelStarterVoltageTrend= NULL;
ui_ImageBattery= NULL;
ui_LabelHouse= NULL;
ui_LabelStarter= NULL;

}
