// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SLS480v3

#ifndef UI_COMPASSSCREEN_H
#define UI_COMPASSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_CompassScreen
extern void ui_CompassScreen_screen_init(void);
extern void ui_CompassScreen_screen_destroy(void);
extern lv_obj_t *ui_CompassScreen;
extern lv_obj_t *ui_ImageCompassRose;
extern lv_obj_t *ui_ImageArrow;
extern lv_obj_t *ui_LabelHeading;
extern lv_obj_t *ui_LabelHeadingMode;
extern lv_obj_t *ui_PanelConnected;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

