// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SLS480v3

#ifndef UI_ENGINESCREEN_H
#define UI_ENGINESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EngineScreen
extern void ui_EngineScreen_screen_init(void);
extern void ui_EngineScreen_screen_destroy(void);
extern lv_obj_t *ui_EngineScreen;
extern lv_obj_t *ui_PanelExhaustTemp;
extern lv_obj_t *ui_ImageExhaustTem;
extern lv_obj_t *ui_LabelExhaustTemp;
extern lv_obj_t *ui_LabelMaxExhaustTemp;
extern lv_obj_t *ui_LabelMinExhaustTemp;
extern lv_obj_t *ui_LabelTrendExhaustTemp;
extern lv_obj_t *ui_ContainerFuelGauge;
extern lv_obj_t *ui_PanelLitresBg;
extern lv_obj_t *ui_LabelLitres;
extern lv_obj_t *ui_LabelLitresTitle;
extern lv_obj_t *ui_LabelEmpty;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_LabelFull;
extern lv_obj_t *ui_ImageFuel;
extern lv_obj_t *ui_ArcFuel;
extern lv_obj_t *ui_Panel12;
extern lv_obj_t *ui_Panel34;
extern lv_obj_t *ui_Panel14;
extern lv_obj_t *ui_PanelEmpty;
extern lv_obj_t *ui_PanelFull;
extern lv_obj_t *ui_ContainerWaterGauge;
extern lv_obj_t *ui_PanelWtrLitresBg;
extern lv_obj_t *ui_LabelWtrLitres;
extern lv_obj_t *ui_LabelWtrLitresTitle;
extern lv_obj_t *ui_LabelWtrEmpty;
extern lv_obj_t *ui_LabelWtr14;
extern lv_obj_t *ui_LabelWtr12;
extern lv_obj_t *ui_LabelWtr34;
extern lv_obj_t *ui_LabelWtrFull;
extern lv_obj_t *ui_ImageWater;
extern lv_obj_t *ui_ArcWater;
extern lv_obj_t *ui_PanelWtr12;
extern lv_obj_t *ui_PanelWtr34;
extern lv_obj_t *ui_PanelWtr14;
extern lv_obj_t *ui_PanelWtrEmpty;
extern lv_obj_t *ui_PanelWtrFull;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

