// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 9.3
// Project name: SLS480v3

#ifndef UI_ENGINESCREEN_H
#define UI_ENGINESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_EngineScreen
extern void ui_EngineScreen_screen_init(void);
extern void ui_EngineScreen_screen_destroy(void);
extern lv_obj_t *ui_EngineScreen;
extern lv_obj_t *ui_PanelExhaustTemp;
extern lv_obj_t *ui_ImageExhaustTem;
extern lv_obj_t *ui_LabelExhaustTemp;
extern lv_obj_t *ui_LabelMaxExhaustTemp;
extern lv_obj_t *ui_LabelMinExhaustTemp;
extern lv_obj_t *ui_LabelTrendExhaustTemp;
extern lv_obj_t *ui_ContainerFuelGauge;
extern lv_obj_t *ui_ImageFuelGauge;
extern lv_obj_t *ui_PanelLitresBg;
extern lv_obj_t *ui_ArcFuel;
extern lv_obj_t *ui_LabelLitres;
extern lv_obj_t *ui_LabelLitresTitle;
extern lv_obj_t *ui_LabelEmpty;
extern lv_obj_t *ui_Label14;
extern lv_obj_t *ui_Label12;
extern lv_obj_t *ui_Label34;
extern lv_obj_t *ui_LabelFull;
extern lv_obj_t *ui_ImageFuel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

