// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#include "ui.h"

lv_obj_t *ui_WeatherScreen = NULL;lv_obj_t *ui_PanelTemperature = NULL;lv_obj_t *ui_ImageTemperature = NULL;lv_obj_t *ui_LabelTemp = NULL;lv_obj_t *ui_LabelMaxTemp = NULL;lv_obj_t *ui_LabelMinTemp = NULL;lv_obj_t *ui_PanelPressure = NULL;lv_obj_t *ui_ImagePressure = NULL;lv_obj_t *ui_LabelPressure = NULL;lv_obj_t *ui_LabelMaxPressure = NULL;lv_obj_t *ui_LabelMinPressure = NULL;lv_obj_t *ui_LabelHpa = NULL;lv_obj_t *ui_LabelTrend = NULL;lv_obj_t *ui_PanelHumidity = NULL;lv_obj_t *ui_ImageHumidity = NULL;lv_obj_t *ui_LabelHumidity = NULL;lv_obj_t *ui_LabelMaxHumidity = NULL;lv_obj_t *ui_LabelMinHumidity = NULL;
// event funtions

// build funtions

void ui_WeatherScreen_screen_init(void)
{
ui_WeatherScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WeatherScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_WeatherScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_WeatherScreen, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelTemperature = lv_obj_create(ui_WeatherScreen);
lv_obj_set_width( ui_PanelTemperature, 480);
lv_obj_set_height( ui_PanelTemperature, 480);
lv_obj_set_align( ui_PanelTemperature, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_PanelTemperature, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelTemperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelTemperature, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelTemperature, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageTemperature = lv_img_create(ui_PanelTemperature);
lv_img_set_src(ui_ImageTemperature, &ui_img_temperature2_png);
lv_obj_set_width( ui_ImageTemperature, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageTemperature, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageTemperature, 0 );
lv_obj_set_y( ui_ImageTemperature, 20 );
lv_obj_set_align( ui_ImageTemperature, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ImageTemperature, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_LabelTemp = lv_label_create(ui_PanelTemperature);
lv_obj_set_width( ui_LabelTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTemp,"+25°C");
lv_obj_clear_flag( ui_LabelTemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTemp, &ui_font_FontHeading96b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxTemp = lv_label_create(ui_PanelTemperature);
lv_obj_set_width( ui_LabelMaxTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxTemp, 0 );
lv_obj_set_y( ui_LabelMaxTemp, 120 );
lv_obj_set_align( ui_LabelMaxTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxTemp,"Max +60°C");
lv_obj_clear_flag( ui_LabelMaxTemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxTemp, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinTemp = lv_label_create(ui_PanelTemperature);
lv_obj_set_width( ui_LabelMinTemp, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinTemp, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinTemp, 0 );
lv_obj_set_y( ui_LabelMinTemp, 160 );
lv_obj_set_align( ui_LabelMinTemp, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinTemp,"Min -60°C");
lv_obj_clear_flag( ui_LabelMinTemp, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinTemp, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinTemp, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelPressure = lv_obj_create(ui_WeatherScreen);
lv_obj_set_width( ui_PanelPressure, 480);
lv_obj_set_height( ui_PanelPressure, 480);
lv_obj_set_align( ui_PanelPressure, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PanelPressure, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelPressure, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelPressure, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelPressure, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImagePressure = lv_img_create(ui_PanelPressure);
lv_img_set_src(ui_ImagePressure, &ui_img_air2_png);
lv_obj_set_width( ui_ImagePressure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImagePressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImagePressure, 0 );
lv_obj_set_y( ui_ImagePressure, 10 );
lv_obj_set_align( ui_ImagePressure, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ImagePressure, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags

ui_LabelPressure = lv_label_create(ui_PanelPressure);
lv_obj_set_width( ui_LabelPressure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelPressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelPressure, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelPressure,"1013");
lv_obj_clear_flag( ui_LabelPressure, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelPressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelPressure, &ui_font_FontHeading96b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxPressure = lv_label_create(ui_PanelPressure);
lv_obj_set_width( ui_LabelMaxPressure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxPressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxPressure, 0 );
lv_obj_set_y( ui_LabelMaxPressure, 120 );
lv_obj_set_align( ui_LabelMaxPressure, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxPressure,"Max 1100");
lv_obj_clear_flag( ui_LabelMaxPressure, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxPressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxPressure, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinPressure = lv_label_create(ui_PanelPressure);
lv_obj_set_width( ui_LabelMinPressure, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinPressure, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinPressure, 0 );
lv_obj_set_y( ui_LabelMinPressure, 160 );
lv_obj_set_align( ui_LabelMinPressure, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinPressure,"Min 850");
lv_obj_clear_flag( ui_LabelMinPressure, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinPressure, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinPressure, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinPressure, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelHpa = lv_label_create(ui_PanelPressure);
lv_obj_set_width( ui_LabelHpa, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHpa, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelHpa, 0 );
lv_obj_set_y( ui_LabelHpa, -80 );
lv_obj_set_align( ui_LabelHpa, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHpa,"hPa");
lv_obj_clear_flag( ui_LabelHpa, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHpa, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHpa, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHpa, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelTrend = lv_label_create(ui_PanelPressure);
lv_obj_set_width( ui_LabelTrend, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelTrend, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelTrend, 0 );
lv_obj_set_y( ui_LabelTrend, 80 );
lv_obj_set_align( ui_LabelTrend, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelTrend,"↓↑");
lv_obj_clear_flag( ui_LabelTrend, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelTrend, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelTrend, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelTrend, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanelHumidity = lv_obj_create(ui_WeatherScreen);
lv_obj_set_width( ui_PanelHumidity, 480);
lv_obj_set_height( ui_PanelHumidity, 480);
lv_obj_set_align( ui_PanelHumidity, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_PanelHumidity, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_PanelHumidity, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_bg_color(ui_PanelHumidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PanelHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_PanelHumidity, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_PanelHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ImageHumidity = lv_img_create(ui_PanelHumidity);
lv_img_set_src(ui_ImageHumidity, &ui_img_humidity2_png);
lv_obj_set_width( ui_ImageHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ImageHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ImageHumidity, 0 );
lv_obj_set_y( ui_ImageHumidity, 20 );
lv_obj_set_align( ui_ImageHumidity, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ImageHumidity, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_LabelHumidity = lv_label_create(ui_PanelHumidity);
lv_obj_set_width( ui_LabelHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelHumidity,"100%");
lv_obj_clear_flag( ui_LabelHumidity, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelHumidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelHumidity, &ui_font_FontHeading96b, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMaxHumidity = lv_label_create(ui_PanelHumidity);
lv_obj_set_width( ui_LabelMaxHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMaxHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMaxHumidity, 0 );
lv_obj_set_y( ui_LabelMaxHumidity, 120 );
lv_obj_set_align( ui_LabelMaxHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMaxHumidity,"Max 100%");
lv_obj_clear_flag( ui_LabelMaxHumidity, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMaxHumidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMaxHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMaxHumidity, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelMinHumidity = lv_label_create(ui_PanelHumidity);
lv_obj_set_width( ui_LabelMinHumidity, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelMinHumidity, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelMinHumidity, 0 );
lv_obj_set_y( ui_LabelMinHumidity, 160 );
lv_obj_set_align( ui_LabelMinHumidity, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelMinHumidity,"Min 0%");
lv_obj_clear_flag( ui_LabelMinHumidity, LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_style_text_color(ui_LabelMinHumidity, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelMinHumidity, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelMinHumidity, &ui_font_FontDialog36, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_WeatherScreen_screen_destroy(void)
{
   if (ui_WeatherScreen) lv_obj_del(ui_WeatherScreen);

// NULL screen variables
ui_WeatherScreen= NULL;
ui_PanelTemperature= NULL;
ui_ImageTemperature= NULL;
ui_LabelTemp= NULL;
ui_LabelMaxTemp= NULL;
ui_LabelMinTemp= NULL;
ui_PanelPressure= NULL;
ui_ImagePressure= NULL;
ui_LabelPressure= NULL;
ui_LabelMaxPressure= NULL;
ui_LabelMinPressure= NULL;
ui_LabelHpa= NULL;
ui_LabelTrend= NULL;
ui_PanelHumidity= NULL;
ui_ImageHumidity= NULL;
ui_LabelHumidity= NULL;
ui_LabelMaxHumidity= NULL;
ui_LabelMinHumidity= NULL;

}
