// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SLS480v2

#ifndef UI_WEATHERSCREEN_H
#define UI_WEATHERSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeatherScreen
extern void ui_WeatherScreen_screen_init(void);
extern void ui_WeatherScreen_screen_destroy(void);
extern lv_obj_t *ui_WeatherScreen;
extern lv_obj_t *ui_PanelTemperature;
extern lv_obj_t *ui_ImageTemperature;
extern lv_obj_t *ui_LabelTemp;
extern lv_obj_t *ui_LabelMaxTemp;
extern lv_obj_t *ui_LabelMinTemp;
extern lv_obj_t *ui_LabelTrendTemp;
extern lv_obj_t *ui_PanelPressure;
extern lv_obj_t *ui_ImagePressure;
extern lv_obj_t *ui_LabelPressure;
extern lv_obj_t *ui_LabelMaxPressure;
extern lv_obj_t *ui_LabelMinPressure;
extern lv_obj_t *ui_LabelHpa;
extern lv_obj_t *ui_LabelTrend;
extern lv_obj_t *ui_PanelHumidity;
extern lv_obj_t *ui_ImageHumidity;
extern lv_obj_t *ui_LabelHumidity;
extern lv_obj_t *ui_LabelMaxHumidity;
extern lv_obj_t *ui_LabelMinHumidity;
extern lv_obj_t *ui_LabelTrendHumidity;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

